name: avua
description: www.avua.com.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  flutter_web_plugins:
    sdk: flutter
  go_router: ^9.0.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  intl: 0.18.0
  lottie: ^2.5.0
  share_plus: ^7.1.0
  url_launcher: ^6.1.12

dev_dependencies:
  device_preview: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/landing_page/
